Repository NVIDIA/Fuser, pull requests merged in 2023-12, with the labels that each got.

#1436 IdModel: Check self mappings
  CMakeLists.txt
  csrc/id_model/id_model.cpp
  csrc/id_model/id_model.h
  test/test_id_model.cpp
Labels: idgraph

#1446 Remove unnecessary input binding.
  csrc/executor.cpp
Labels: cleanup

#1402 Refactor Automatic Serialization API
  csrc/kernel_cache.cpp
  csrc/kernel_cache.h
  csrc/python_frontend/fusion_cache.cpp
  csrc/python_frontend/fusion_cache.h
  csrc/python_frontend/python_bindings.cpp
  nvfuser/__init__.py
  python_tests/test_python_frontend.py
Labels: serde

#1457 IdModel: cleanup almost exact
  csrc/device_lower/lower2device.cpp
  csrc/id_model/id_model.cpp
  csrc/id_model/validation_utils.cpp
  csrc/id_model/validation_utils.h
  csrc/val_graph.cpp
  csrc/val_graph.h
Labels: idgraph

#1485 Remove the unused `inputs` parameter.
  csrc/executor.cpp
Labels: cleanup

#1440 Serialize Fusion Segmentation
  csrc/fusion_segmenter.cpp
  csrc/fusion_segmenter.h
  csrc/ir/container.cpp
  csrc/ir/container.h
  csrc/kernel_cache.cpp
  csrc/kernel_cache.h
  csrc/python_frontend/fusion_cache.cpp
  csrc/serde/fusion_cache.fbs
Labels: serde

#1498 Add test_segmentation.cpp back to CMakeLists.txt.
  CMakeLists.txt
Labels: bug

#1489 Fix a bug related to expanded broadcast IterDomains.
  csrc/optimization/alias_analysis.cpp
  test/test_alias.cpp
Labels: bug

#1490 Move some logic from MarkAliasPass to AliasAnalysis.
  csrc/optimization/alias_analysis.cpp
  csrc/optimization/alias_analysis.h
  csrc/optimization/mark_alias.cpp
  test/test_alias.cpp
Labels: cleanup

#1492 Relax the allocation domain constraint.
  csrc/optimization/alias_analysis.cpp
  csrc/optimization/alias_analysis.h
  csrc/optimization/mark_alias.cpp
  test/test_alias.cpp
Labels: enhancement

#1511 Fix mapping propagation through backward merge
  csrc/id_model/id_model.cpp
  csrc/id_model/validation_utils.cpp
  csrc/id_model/validation_utils.h
  csrc/val_graph.cpp
Labels: idgraph

#1478 Mark aliases during scheduling.
  CMakeLists.txt
  csrc/device_lower/pass/expr_sort.cpp
  csrc/fusion.cpp
  csrc/fusion_segmenter.cpp
  csrc/optimization/alias_analysis.cpp
  csrc/optimization/alias_analysis.h
  csrc/optimization/optimize_layout.cpp
  csrc/optimization/optimize_layout.h
  csrc/optimization/pre_segmenter.cpp
  csrc/scheduler/mark_aliases.cpp
  csrc/scheduler/mark_aliases.h
  csrc/scheduler/no_op.cpp
  csrc/scheduler/pointwise.cpp
  test/test_alias.cpp
  test/test_gpu_transpose.cpp
Labels: enhancement

#1521 Clean up test_segmentation.cpp and add another test for `segment_set`.
  test/test_segmentation.cpp
Labels: testing

#1544 Fix bug in codediff for pytest
  tools/codediff/compare_codegen.sh
  tools/codediff/diff_report.py
  tools/codediff/templates/test_diff_section.html
Labels: testing

#1545 Disable split-K benchmarks temporarily
  benchmark/matmul.cpp
Labels: matmul, testing

#1547 Clean up comment in test_issue1277
  python_tests/test_python_frontend.py
Labels: documentation, cleanup

#1539 Rename OptimizeLayoutPass.
  CMakeLists.txt
  csrc/alias_analysis.h
  csrc/optimization/mark_aliases_prepare.cpp
  csrc/optimization/mark_aliases_prepare.h
  csrc/optimization/pre_segmenter.cpp
  test/test_gpu_transpose.cpp
Labels: cleanup
