Repository NVIDIA/Fuser, pull requests merged in 2023-11, with the labels that each got.

#1205 Move no-op scheduler tests to test/test_no_op.cpp.
  test/test_gpu3.cpp
  test/test_no_op.cpp
Labels: cleanup

#1206 Minor cleanups to the Python API for normalization and its test.
  nvfuser/contrib/nn/normalization.py
  python_tests/test_normalization.py
Labels: cleanup

#1213 Use self.exec_nvfuser to run a fusion.
  python_tests/test_python_frontend.py
Labels: testing

#1203 Generate an empty kernel when all outputs are aliases.
  CMakeLists.txt
  csrc/fusion.cpp
  csrc/optimization/alias_analysis.cpp
  csrc/optimization/alias_analysis.h
  csrc/optimization/mark_alias.cpp
  csrc/optimization/mark_alias.h
  csrc/optimization/pre_segmenter.cpp
  csrc/scheduler/no_op.cpp
  test/test_alias_analysis.cpp
  test/test_no_op.cpp
Labels: enhancement

#1219 Remove debug print.
  csrc/optimization/mark_alias.cpp
Labels: cleanup

#1230 Remove a redundant anonymous namespace.
  csrc/executor.cpp
Labels: cleanup

#1231 Cleanup: extract `allocateOutput` as a separate function.
  csrc/executor.cpp
Labels: cleanup

#1232 Remove the special handling for trivial forwarding.
  csrc/executor.cpp
  csrc/kernel_cache.cpp
  test/test_gpu3.cpp
Labels: cleanup

#1253 Check allocation domain and contiguity of aliased tensors.
  csrc/executor.cpp
  csrc/tensor_metadata.cpp
  csrc/tensor_metadata.h
Labels: testing

#1258 Cleanup test_gpu_transpose.cpp.
  test/test_gpu_transpose.cpp
Labels: cleanup

#1257 AliasAnalysis handles `Set.Permute`.
  csrc/ir/nodes.cpp
  csrc/ir/utils.h
  csrc/optimization/alias_analysis.cpp
  csrc/optimization/alias_analysis.h
  csrc/optimization/mark_alias.cpp
  csrc/options.cpp
  csrc/options.h
  nvfuser/contrib/nn/normalization.py
  test/test_alias.cpp
  test/test_gpu_transpose.cpp
Labels: enhancement

#1271 Add variants of `slice` that takes `int64_t`s.
  csrc/ops/alias.cpp
  csrc/ops/alias.h
  csrc/python_frontend/fusion_record.h
  csrc/python_frontend/python_bindings.cpp
  test/test_resize.cpp
Labels: enhancement

#1274 `SliceOp::in` and `::out` return `TensorView*` instead of `Val*`.
  csrc/ir/internal_nodes.h
Labels: cleanup

#1276 Add Layout::toString for debugging.
  csrc/ir/internal_base_nodes.h
  csrc/optimization/alias_analysis.cpp
  csrc/optimization/alias_analysis.h
  csrc/type.cpp
  csrc/type.h
  csrc/utils.h
Labels: enhancement

#1282 Add LinkedHashMap and unit tests.
  CMakeLists.txt
  csrc/linked_hash_map.h
  test/test_linked_hash_map.cpp
Labels: enhancement

#1288 Add the missed `#pragma once`.
  csrc/optimization/alias_analysis.h
Labels: bug

#1287 Print fusion IR with transforms after concretization.
  csrc/kernel_cache.cpp
Labels: enhancement

#1293 Mechanical changes extracted from #1168
  CMakeLists.txt
  csrc/disjoint_set.h
  csrc/id_model/id_model.cpp
  csrc/id_model/id_model.h
  csrc/id_model/to_string.cpp
  csrc/id_model/to_string.h
  csrc/id_model/visitor.cpp
  csrc/id_model/visitor.h
  csrc/val_graph.cpp
  csrc/val_graph.h
  test/test_gpu_indexing.cpp
Labels: idgraph

#1168 IdModel: Reproduce exact map
  CMakeLists.txt
  csrc/compute_at_map.h
  csrc/device_lower/lower2device.cpp
  csrc/disjoint_set.h
  csrc/expr_evaluator.cpp
  csrc/id_model/id_model.cpp
  csrc/id_model/id_model.h
  csrc/id_model/to_string.cpp
  csrc/id_model/to_string.h
  csrc/id_model/validation_utils.cpp
  csrc/id_model/validation_utils.h
  csrc/ir/utils.cpp
  csrc/ir/utils.h
  csrc/options.cpp
  csrc/options.h
  csrc/val_graph.cpp
  csrc/val_graph.h
Labels: idgraph

#1292 Move implementation to cpp.
  csrc/kernel.cpp
  csrc/kernel.h
Labels: cleanup

#1308 Minor cleanups.
  test/test_linked_hash_map.cpp
Labels: cleanup

#1291 TransformReplay::replayCasP sets the right contiguity.
  csrc/transform_replay.cpp
  test/test_allocation_domain.cpp
Labels: bug

#1281 AliasAnalysis handles slices.
  csrc/executor.cpp
  csrc/fusion.cpp
  csrc/fusion.h
  csrc/optimization/alias_analysis.cpp
  csrc/optimization/mark_alias.cpp
  test/test_alias.cpp
Labels: enhancement

#1332 Minor cleanup to reduce indentation.
  csrc/optimization/mark_alias.cpp
Labels: cleanup

#1333 Remove Fusion::ioAlias.
  csrc/executor.cpp
  csrc/fusion.cpp
  csrc/fusion.h
  csrc/kernel_cache.cpp
  csrc/scheduler/registry_utils.cpp
  test/validator.h
Labels: cleanup

#1363 Alloc domain patch concretization
  csrc/dynamic_transform.cpp
  python_tests/test_python_frontend.py
Labels: allocation domain

#1379 Print runtime info for debugging.
  csrc/scheduler/normalization_inner_outer.cpp
Labels: documentation

#1397 Skip stride_order when it is a canonical row-major storage.
  csrc/python_frontend/fusion_record.h
Labels: allocation domain

#1422 Move IterVisitor tests to a separate file.
  CMakeLists.txt
  test/test_gpu3.cpp
  test/test_iter_visitor.cpp
Labels: cleanup
