Repository NVIDIA/Fuser, pull requests merged in 2023-10, with the labels that each got.

#1072 Fix mapping propagations through uses
  csrc/id_model/id_graph.cpp
Labels: idgraph

#1082 Disable mappings of non-ca domains in LOOP.
  csrc/id_model/id_graphs.cpp
  csrc/python_frontend/fusion_record.h
  csrc/python_frontend/python_bindings.cpp
  csrc/python_frontend/test/test_nvfuser_fusion_record.cpp
  csrc/scheduler/mma_utils.cpp
  csrc/utils.h
Labels: idgraph

#1087 Remove unnecessary code
  csrc/id_model/id_graphs.cpp
Labels: idgraph

#1090 WIP: Loop promotion with IEL
  csrc/id_model/id_graphs.cpp
  test/test_gpu_indexing.cpp
Labels: idgraph

#1102 contig map should use alloc_domain for contiguity check
  csrc/scheduler/vectorize_helper.cpp
Labels: allocation domain

#1100 enabling allocation domain on TensorViewBuilder
  csrc/ir/interface_nodes.h
  csrc/ir/internal_base_nodes.h
  csrc/ir/nodes.cpp
  csrc/python_frontend/python_bindings.cpp
  csrc/tensor_view.cpp
  test/test_allocation_domain.cpp
Labels: allocation domain

#1107 switch to TensorDomain constructor to set allocation_domain
  csrc/fusion_segmenter.cpp
  test/test_allocation_domain.cpp
Labels: allocation domain

#1031 Stride order input enablement
  csrc/python_frontend/fusion_record.h
  csrc/python_frontend/python_bindings.cpp
  csrc/serde/fusion_cache.fbs
  csrc/serde/fusion_record_serde.cpp
  python_tests/pytest_input_generators.py
  python_tests/test_python_frontend.py
  version.txt
Labels: allocation domain

#1113 Fixing allocation domain for index_select
  csrc/index_compute.cpp
  python_tests/test_python_frontend.py
Labels: allocation domain

#1144 Fix use of replayed input IDs
  csrc/id_model/id_graphs.cpp
Labels: idgraph

#1141 pushTensorProxy except for trivial forwarding.
  csrc/executor.cpp
  test/test_gpu3.cpp
Labels: cleanup

#1149 Finalize loop promotion map
  csrc/id_model/id_graph.cpp
  csrc/id_model/id_graph.h
  csrc/id_model/id_graphs.cpp
Labels: idgraph

#1161 Renaming IterDomainGraphs to IdModel
  csrc/device_lower/lower2device.cpp
  csrc/id_model/id_graphs.cpp
  csrc/id_model/id_graphs.h
  test/test_gpu_indexing.cpp
Labels: idgraph

#1165 Follow-up to #1161
  csrc/id_model/id_model.cpp
  csrc/id_model/id_model.h
Labels: idgraph

#1150 More cleanups around trivial input forwarding and aliasing.
  csrc/executor.cpp
  csrc/executor.h
  csrc/kernel_cache.cpp
  test/test_gpu3.cpp
Labels: cleanup

#1170 Implement `ViewOp::evaluate`.
  csrc/ir/internal_nodes.h
  csrc/ir/nodes.cpp
  test/test_evaluator.cpp
Labels: enhancement

#1181 Dedup code.
  csrc/fusion_segmenter.h
Labels: cleanup

#1184 Remove dead code.
  csrc/executor_utils.cpp
  csrc/executor_utils.h
Labels: cleanup

#1180 Print the missing key.
  csrc/kernel_cache.cpp
Labels: cleanup

#1182 Forbid non-tensor outputs.
  csrc/executor.cpp
  csrc/fusion.cpp
  csrc/multidevice/pipeline_ir.cpp
  test/test_gpu1.cpp
Labels: bug
