Repository NVIDIA/Fuser, pull requests merged in 2024-02, with the labels that each got.

#1714 Make sure ValGraphs are created deterministically
  csrc/id_model/id_model.cpp
Labels: idmodel

#1722 Add the missing `clang-format on` and reformat.
  test/test_pointwise.cpp
Labels: cleanup

#1720 Print a newline before the header.
  csrc/fusion_profiler.cpp
Labels: cleanup

#1650 IdModel: Loop Promotion Analysis Step 1: Build a map of broadcast resolutions for root domains
  csrc/disjoint_set.h
  csrc/id_model/id_model.cpp
  csrc/id_model/id_model.h
  csrc/val_graph.h
  test/test_id_model.cpp
Labels: idmodel

#1755 Layout propagation (Part 2) - Enable
  csrc/preseg_passes/allocation_order_inference.cpp
  csrc/preseg_passes/allocation_order_inference.h
  csrc/preseg_passes/pre_segmenter.cpp
  test/test_allocation_order_inference.cpp
Labels: allocation domain

#1795 Pass allow_self_mapping to IterDomainGraph.
  csrc/compute_at_map.cpp
  csrc/compute_at_map.h
  csrc/id_model/id_model.cpp
  csrc/id_model/validation_utils.cpp
  csrc/id_model/validation_utils.h
  test/test_id_model.cpp
Labels: bug, idmodel
