Repository NVIDIA/Fuser, pull requests merged in 2024-05, with the labels that each got.

#2200 Fix TensorView::clearReductionIterDomains specifies wrong contiguity flag
  csrc/tensor_view.cpp
  tests/cpp/test_allocation_domain.cpp
Labels: allocation domain

#2229 Add test that external matmul plugin is loaded properly
  tests/cpp/test_matmul_scheduler.cpp
Labels: matmul

#2220 IdModel: Step 5 of the loop promotion analysis
  csrc/id_model/id_model.cpp
  csrc/id_model/id_model.h
  tests/cpp/test_id_model.cpp
Labels: idmodel

#2270 Shortest path between ValGroups in ValGraph
  csrc/val_graph_visitor.cpp
  csrc/val_graph_visitor.h
  tests/cpp/test_id_model.cpp
Labels: idmodel

#2232 IdModel: loop promotion cleanup
  CMakeLists.txt
  csrc/id_model/id_model.cpp
  csrc/id_model/id_model.h
  csrc/id_model/loop_promotion.cpp
  csrc/id_model/loop_promotion.h
  tests/cpp/test_id_model.cpp
Labels: idmodel

#2239 Map sibling domains in the LOOP graph
  csrc/disjoint_set.h
  csrc/id_model/id_model.cpp
  csrc/id_model/id_model.h
  tests/cpp/test_id_model.cpp
Labels: idmodel

#2300 Compute matmul dim roles with no-devices leaf domain
  csrc/scheduler/mma_utils.cpp
Labels: bug, matmul, Multidevice

#2313 Loop promotion fix for #2261
  csrc/id_model/loop_promotion.cpp
  csrc/id_model/loop_promotion.h
  tests/cpp/test_id_model.cpp
Labels: idmodel
