Repository NVIDIA/Fuser, pull requests merged in 2024-01, with the labels that each got.

#1589 IdModel: refactoring loop promotion
  csrc/id_model/id_model.cpp
  csrc/id_model/id_model.h
  csrc/id_model/transform_replay.cpp
  csrc/id_model/transform_replay.h
  test/test_gpu_indexing.cpp
Labels: idmodel

#1598 Add type annotation and clean imports.
  python_benchmarks/core.py
Labels: cleanup

#1569 IdModel: Add an initial loop graph (no promotion yet)
  csrc/id_model/id_model.cpp
  csrc/id_model/id_model.h
  csrc/val_graph.cpp
  csrc/val_graph.h
Labels: idmodel

#1617 Fix a bug that potentially blocks #1502.
  csrc/scheduler/pointwise.cpp
  csrc/scheduler/reduction.cpp
  test/test_alias.cpp
Labels: bug

#1620 Pointwise scheduler to accommodate allocation domain
  csrc/scheduler/compile_time_info.h
  csrc/scheduler/pointwise.cpp
  csrc/scheduler/pointwise_heuristic.h
  csrc/scheduler/registry.cpp
  csrc/scheduler/utils.cpp
  csrc/scheduler/utils.h
  csrc/scheduler/vectorize_helper.cpp
  csrc/scheduler/vectorize_helper.h
  test/test_pointwise.cpp
Labels: allocation domain

#1637 [IdModle] Val graph cleanup
  csrc/id_model/id_model.cpp
  csrc/id_model/to_string.cpp
  csrc/id_model/visitor.cpp
  csrc/val_graph.cpp
  csrc/val_graph.h
Labels: idmodel

#1624 [IdModel] Refactoring for testing
  csrc/device_lower/lower2device.cpp
  csrc/id_model/id_model.cpp
  csrc/id_model/id_model.h
  test/test_gpu_indexing.cpp
  test/test_id_model.cpp
Labels: idmodel

#1644 [IdModel] Cherry pick #1627
  csrc/id_model/id_model.cpp
  csrc/val_graph.cpp
  csrc/val_graph.h
Labels: idmodel

#1648 Refactoring to allow more flexible testing
  csrc/device_lower/lower2device.cpp
  csrc/id_model/id_model.cpp
  csrc/id_model/id_model.h
Labels: idmodel

#1686 Some cleanups around in-place-update aliases and their tests.
  csrc/fusion_segmenter.cpp
  csrc/fusion_segmenter.h
  test/test_alias.cpp
  test/test_gpu2.cpp
  test/validator.h
Labels: cleanup
