Repository NVIDIA/Fuser, pull requests merged in 2024-11, with the labels that each got.

#3324 Add cuda arch guard to skip ampere matmul tests on Hopper GPUs
  tests/cpp/test_matmul.cpp
  tests/cpp/test_matmul_sass.cpp
  tests/cpp/test_matmul_scheduler.cpp
Labels: Matmuls, Top-Down Matmul Dev

#3352 Move allocOutputSpace to multidevice/executor.cpp
  csrc/multidevice/executor.cpp
  csrc/runtime/allocations.cpp
  csrc/runtime/allocations.h
Labels: cleanup

#3326 Clean uses of unique_ptr.
  tests/cpp/test_allocation_domain.cpp
Labels: cleanup

#3320 Load mma operands to shared memory with TMA
  csrc/index_compute.cpp
  csrc/scheduler/hopper_multi_matmul.cpp
  csrc/scheduler/hopper_multi_matmul.h
  tests/cpp/test_matmul.cpp
  tests/cpp/test_matmul_scheduler.cpp
  tests/cpp/test_multidevice_matmul.cpp
Labels: Matmuls, Top-Down Matmul Dev

#3357 Set `fusion_id` and `device_id` of `KernelExecutor` in constructor for user scheduling.
  csrc/python_frontend/fusion_cache.cpp
  csrc/python_frontend/fusion_cache.h
  csrc/python_frontend/fusion_definition.cpp
  csrc/runtime/fusion_kernel_runtime.cpp
Labels: Python API

#3380 Rename addSetsForCacheReads to cacheOperandsToRegisters
  csrc/scheduler/ampere_multi_matmul.cpp
  csrc/scheduler/ampere_multi_matmul.h
Labels: Matmuls, cleanup

#3377 Change a functor to a regular function.
  tests/cpp/test_sdpa_node.cpp
Labels: cleanup

#3384 Remove debug prints
  tests/cpp/test_id_model.cpp
Labels: cleanup

#3278 Schedule Hopper mma instruction
  csrc/scheduler/hopper_multi_matmul.cpp
  csrc/scheduler/hopper_multi_matmul.h
  tests/cpp/test_matmul_scheduler.cpp
Labels: Matmuls

#3334 Build Segments for User Schedule Segmentation
  CMakeLists.txt
  csrc/python_frontend/fusion_definition.cpp
  csrc/python_frontend/fusion_definition.h
  csrc/python_frontend/fusion_state.cpp
  csrc/python_frontend/fusion_state.h
  csrc/python_frontend/python_bindings.cpp
  csrc/python_frontend/segmentation.cpp
  csrc/python_frontend/segmentation.h
  nvfuser/__init__.py
  tests/python/test_python_frontend.py
Labels: Python API

#3335 Translate segments to python definition
  csrc/python_frontend/fusion_definition.cpp
  csrc/python_frontend/fusion_definition.h
  csrc/python_frontend/python_bindings.cpp
  csrc/python_frontend/segmentation.cpp
  csrc/python_frontend/segmentation.h
  nvfuser/__init__.py
  tests/python/test_python_frontend.py
Labels: Python API

#3418 Add `unsafeBind` to `LaunchParams` to allow modification.
  csrc/python_frontend/python_bindings.cpp
  csrc/runtime/executor_params.cpp
  csrc/runtime/executor_params.h
Labels: Python API

#3443 Fix gdimz in LaunchParams
  csrc/python_frontend/python_bindings.cpp
Labels: Python API

#3431 Add ReductionParams to python frontend
  csrc/python_frontend/python_bindings.cpp
Labels: Autotune

#3432 Fix the setting of `gdimx` in 2d and 3d inner reduction heuristics
  csrc/scheduler/reduction.cpp
Labels: Schedulers & Heuristics

#3460 Remove an unnecessary segment_set.
  tests/cpp/test_multidevice_matmul.cpp
Labels: cleanup

#3025 Enable segmentation support to python frontend user-scheduling
  csrc/python_frontend/python_bindings.cpp
  csrc/python_frontend/segmentation.cpp
  nvfuser/__init__.py
  tests/python/test_ops.py
  tests/python/test_python_frontend.py
  tests/python/utils.py
Labels: Python API

#3381 Remove MatMulTileOptions::instruction_tile
  benchmarks/cpp/matmul.cpp
  csrc/mma_type.cpp
  csrc/mma_type.h
  csrc/python_frontend/python_bindings.cpp
  csrc/scheduler/ampere_multi_matmul.cpp
  csrc/scheduler/matmul_heuristic.h
  csrc/scheduler/matmul_heuristic_plugin.cpp
  csrc/scheduler/matmul_utils.cpp
  csrc/scheduler/mma_utils.cpp
  csrc/scheduler/mma_utils.h
  tests/cpp/test_matmul.cpp
  tests/cpp/test_matmul_sass.cpp
  tests/cpp/test_matmul_scheduler.cpp
  tests/cpp/test_translate_mma.cpp
Labels: Matmuls, cleanup

#3404 Parametrize Hopper matmul tests
  tests/cpp/test_matmul_scheduler.cpp
Labels: Matmuls

#3454 (Yet another) indexing war for resize
  csrc/id_model/id_model_index_compute.h
  csrc/id_model/indexing.cpp
  csrc/id_model/indexing.h
  csrc/id_model/indexing_traversal.cpp
  csrc/id_model/indexing_traversal.h
  csrc/id_model/utils.h
  csrc/index_compute.cpp
  tests/cpp/test_indexing.cpp
Labels: rope
