Repository NVIDIA/Fuser, pull requests merged in 2024-04, with the labels that each got.

#2048 [cleanup] Sort lists in CMakeLists
  CMakeLists.txt
Labels: build, cleanup

#2059 IdModel: Always require promotion to loop mapped domains
  csrc/id_model/id_model.cpp
  csrc/id_model/id_model.h
  tests/cpp/test_id_model.cpp
Labels: idmodel

#2089 Add missing license headers to benchmarks and tests
  .github/workflows/lint.yml
  benchmarks/python/__init__.py
  benchmarks/python/conftest.py
  benchmarks/python/core.py
  benchmarks/python/global_params.py
  benchmarks/python/normalization.py
  benchmarks/python/test_batchnorm_bwd.py
  benchmarks/python/test_batchnorm_fwd.py
  benchmarks/python/test_dropout_layernorm_bwd.py
  benchmarks/python/test_dropout_layernorm_fwd.py
  benchmarks/python/test_dropout_rmsnorm_bwd.py
  benchmarks/python/test_dropout_rmsnorm_fwd.py
  benchmarks/python/test_gelu_bwd.py
  benchmarks/python/test_gelu_bwd_reduction.py
  benchmarks/python/test_gelu_fwd.py
  benchmarks/python/test_huggingface_attn_bwd.py
  benchmarks/python/test_huggingface_attn_fwd.py
  benchmarks/python/test_instancenorm_bwd.py
  benchmarks/python/test_instancenorm_fwd.py
  benchmarks/python/test_layernorm_bwd.py
  benchmarks/python/test_layernorm_fwd.py
  benchmarks/python/test_nanogpt_attn_bwd.py
  benchmarks/python/test_nanogpt_attn_fwd.py
  benchmarks/python/test_reduction.py
  benchmarks/python/test_rmsnorm_bwd.py
  benchmarks/python/test_rmsnorm_fwd.py
  benchmarks/python/test_rope.py
  benchmarks/python/test_scale_bias_relu_bwd.py
  benchmarks/python/test_scale_bias_relu_fwd.py
  benchmarks/python/test_silu_mul_bwd.py
  benchmarks/python/test_silu_mul_fwd.py
  benchmarks/python/test_softmax_bwd.py
  benchmarks/python/test_softmax_fwd.py
  benchmarks/python/test_transpose.py
  csrc/exceptions.cpp
  csrc/exceptions.h
  csrc/multidevice/c10d_mock.h
  csrc/serde/utils.cpp
  examples/sinh_libtorch/main.cpp
  nvfuser/contrib/__init__.py
  nvfuser/contrib/nn/__init__.py
  nvfuser/contrib/nn/normalization.py
  nvfuser/utils.py
  setup.py
  tests/cpp/test_ca_root_domain_map.cpp
  tests/cpp/test_combined_inner_outer_reduction.cpp
  tests/cpp/test_exceptions.cpp
  tests/cpp/test_persistent_buffer.cpp
  tests/cpp/test_reduction_pointwise.cpp
  tests/python/mpi_test.py
  tests/python/test_nan.py
  tests/python/test_normalization.py
  tools/__init__.py
  tools/examples/repro.cpp
  tools/examples/repro.py
Labels: cleanup

#2138 Add support for 0-dim bias argument in Linear
  csrc/scheduler/mma_utils.cpp
  tests/python/test_python_frontend.py
Labels: Top-Down Matmul Dev

#2152 Use macros to reduce duplication in dispatch.{cpp,h}
  csrc/dispatch.cpp
  csrc/dispatch.h
Labels: cleanup
