Repository NVIDIA/Fuser, pull requests merged in 2024-07, with the labels that each got.

#2500 Fix for when allocation domains are promoted to reduction domains
  csrc/id_model/indexing.cpp
  tests/cpp/test_indexing.cpp
Labels: idmodel

#2527 Separate the computation of `aliased_outs` to a different loop.
  csrc/preseg_passes/mark_aliases_prepare.cpp
Labels: cleanup

#2521 [Python Frontend] Add Jupyter notebook of creating a user scheduled fusion.
  doc/dev/python_scheduling/interactive_scheduling_layer_norm.ipynb
  doc/dev/python_scheduling/tutorial_scheduling_layer_norm.py
Labels: Python API

#2516 Support indexing of unrolled domains
  csrc/device_lower/pass/index.cpp
  csrc/device_lower/pass/index.h
  csrc/id_model/indexing.cpp
  csrc/id_model/indexing.h
  tests/cpp/test_indexing.cpp
Labels: idmodel

#2522 Reorder allocation domains to align with logical domains
  csrc/id_model/indexing.cpp
  tests/cpp/test_indexing.cpp
Labels: idmodel

#2523 Just change the ordering of multiplications when linearizing indices
  csrc/id_model/indexing.cpp
  tests/cpp/test_indexing.cpp
Labels: idmodel

#2536 Patch for allocation domains of shmem tensors used for transpose
  csrc/id_model/indexing.cpp
  tests/cpp/test_indexing.cpp
Labels: idmodel

#2550 Support resize
  csrc/id_model/indexing.cpp
  csrc/id_model/indexing.h
  csrc/id_model/indexing_traversal.h
  csrc/val_graph_visitor.cpp
  csrc/val_graph_visitor.h
  tests/cpp/test_indexing.cpp
Labels: idmodel

#2581 [Python Frontend] Add cache_fork to user-scheduling
  csrc/python_frontend/python_bindings.cpp
  tests/python/test_schedule_ops.py
Labels: Python API

#2288 Select CompileParams for TMA operations automatically at compile-time
  csrc/executor.cpp
  tests/python/test_schedule_ops.py
Labels: Python API, TMA

#2591 Do not attempt to parallelize non-loop domains
  csrc/id_model/id_model.cpp
Labels: idmodel

#2592 Add generate_pointer support
  csrc/index_compute.cpp
Labels: idmodel

#2542 [Python Frontend] Use heuristic schedulers in user-defined schedules
  csrc/python_frontend/fusion_cache.cpp
  csrc/python_frontend/fusion_cache.h
  csrc/python_frontend/fusion_definition.cpp
  csrc/python_frontend/fusion_definition.h
  csrc/python_frontend/python_bindings.cpp
  tests/python/test_schedule_ops.py
Labels: Python API

#2573 [Python Frontend] Concretize fusion for user-defined schedules
  csrc/dynamic_transform.cpp
  csrc/dynamic_transform.h
  csrc/python_frontend/fusion_cache.h
  csrc/python_frontend/fusion_definition.cpp
  tests/python/test_schedule_ops.py
Labels: Python API

#2587 Support indexing for circular buffering
  CMakeLists.txt
  csrc/id_model/circular_buffer_indexing.cpp
  csrc/id_model/circular_buffer_indexing.h
  csrc/id_model/indexing.cpp
  csrc/id_model/indexing.h
  csrc/id_model/indexing_utils.h
  csrc/index_compute.cpp
  tests/cpp/test_indexing.cpp
Labels: idmodel

#2620 [Python Frontend] Schedule new values created by composite operations
  csrc/dynamic_transform.cpp
  csrc/dynamic_transform.h
  csrc/fusion.cpp
  csrc/python_frontend/fusion_definition.cpp
  csrc/python_frontend/fusion_definition.h
  csrc/python_frontend/fusion_state.cpp
  tests/python/test_schedule_ops.py
Labels: Python API

#2677 Predicate indexing for circular buffering
  csrc/id_model/circular_buffer_indexing.cpp
  csrc/id_model/circular_buffer_indexing.h
  csrc/id_model/indexing.cpp
  csrc/id_model/predicate_indexing.cpp
  csrc/id_model/utils.h
  csrc/index_compute.cpp
  csrc/index_compute.h
  csrc/predicate_compute.cpp
  csrc/predicate_compute.h
  tests/cpp/test_indexing.cpp
Labels: idmodel

#2689 Make sure unswitch predicates propagate maximum (or minimum) indices through merge-inner or split-outer domains
  csrc/id_model/indexing.cpp
  csrc/id_model/indexing_utils.h
  csrc/id_model/predicate_indexing.cpp
  csrc/id_model/predicate_indexing.h
  tests/cpp/test_gpu3.cpp
  tests/cpp/test_indexing.cpp
Labels: idmodel

#2691 Predication of non-divisible splits
  csrc/id_model/indexing.cpp
  csrc/index_compute.cpp
  csrc/index_compute.h
  tests/cpp/test_indexing.cpp
Labels: idmodel

#2712 Fix finding right non-divisible splits to predicate
  csrc/id_model/indexing.cpp
  csrc/id_model/indexing.h
  csrc/id_model/predicate_indexing.h
  csrc/index_compute.h
  csrc/predicate_compute.cpp
  csrc/predicate_compute.h
  tests/cpp/test_indexing.cpp
Labels: idmodel
