Repository NVIDIA/Fuser, pull requests merged in 2024-09, with the labels that each got.

#2897 Further WAR for indexing resize
  CMakeLists.txt
  csrc/id_model/indexing_traversal.cpp
  csrc/id_model/indexing_traversal.h
  tests/cpp/test_resize.cpp
Labels: idmodel, rope

#2898 Add slice tests to demonstrate manual scheduling
  csrc/device_lower/lower2device.cpp
  csrc/device_lower/validation.cpp
  csrc/device_lower/validation.h
  tests/cpp/test_resize.cpp
Labels: rope

#2860 Contiguous predicate indexing
  csrc/id_model/contiguity.cpp
  csrc/id_model/contiguity.h
  csrc/id_model/indexing.cpp
  tests/cpp/test_indexing.cpp
Labels: idmodel

#2905 Fix reference implementations and improve validation.
  csrc/ops/composite.cpp
  tests/cpp/test_multidevice_transformer.cpp
  tests/cpp/validator.cpp
Labels: bug

#2943 Simplify FusionDefinition.execute.
  nvfuser/__init__.py
Labels: cleanup

#2939 Add the Broadcast graph
  csrc/compute_at_map.cpp
  csrc/id_model/id_model.cpp
  csrc/id_model/id_model.h
  csrc/type.cpp
  csrc/type.h
  tests/cpp/test_id_model.cpp
Labels: idmodel

#2944 Initialize size_ and local_size_ to 1.
  csrc/multidevice/communicator.cpp
  tests/cpp/test_multidevice_matmul.cpp
  tests/cpp/test_multidevice_transformer.cpp
Labels: bug

#2977 Add an experimental option to map cloned IterDomains in the Exact graph
  csrc/fusion.cpp
  csrc/fusion.h
  csrc/id_model/id_model.cpp
  csrc/ir/cloner.h
  csrc/ir/internal_base_nodes.h
  csrc/ir/nodes.cpp
  tests/cpp/test_id_model.cpp
Labels: rope

#2984 Fix TensorDomain::allIDs when loop domain has extra IDs
  csrc/ir/nodes.cpp
  tests/cpp/test_gpu3.cpp
Labels: rope

#2980 Allow profiling a benchmark iteration.
  tests/python/test_transformer_engine.py
Labels: enhancement

#3003 Support non-conventional loop domains in TensorView::updateMaxProducerPosition.
  csrc/tensor_view.cpp
  tests/cpp/test_inlining.cpp
Labels: rope
