Repository NVIDIA/Fuser, pull requests merged in 2024-03, with the labels that each got.

#1799 Optimize split->reshape/permute->cat.
  csrc/preseg_passes/move_split_cat.cpp
  test/test_move_split_cat.cpp
Labels: enhancement

#1880 sameIterDomainTransforms clones IdGraph.
  csrc/id_model/id_model.cpp
  csrc/id_model/id_model.h
  csrc/preseg_passes/move_split_cat.cpp
  csrc/val_graph.cpp
  csrc/val_graph.h
  test/test_id_model.cpp
  test/test_move_split_cat.cpp
Labels: enhancement

#1879 Simplify some tests in test_id_model.cpp.
  test/test_id_model.cpp
Labels: cleanup

#1777 IdModel: Loop promotion analysis step 2
  CMakeLists.txt
  csrc/id_model/id_model.cpp
  csrc/id_model/id_model.h
  csrc/id_model/transform_replay.cpp
  csrc/id_model/transform_replay.h
  csrc/val_graph.cpp
  csrc/val_graph.h
  test/test_id_model.cpp
Labels: idmodel

#1855 Add DEBUG_SERDE flag to python tests
  python_tests/test_python_frontend.py
Labels: serde

#1909 Remove unused dtype parameter in ops::newOutputDomain
  csrc/ops/alias.cpp
  csrc/ops/utils.cpp
  csrc/ops/utils.h
Labels: cleanup

#1830 IdModel: Loop promotion analysis step 3
  csrc/id_model/id_model.cpp
  csrc/id_model/id_model.h
  test/test_id_model.cpp
Labels: idmodel
