Repository NVIDIA/Fuser, pull requests merged in 2024-12, with the labels that each got.

#3473 Support TMA store in hopper matmul scheduler.
  csrc/scheduler/hopper_multi_matmul.cpp
  csrc/scheduler/hopper_multi_matmul.h
  tests/cpp/test_matmul_scheduler.cpp
Labels: Matmuls

#3499 Add StMatrix support to hopper matmul scheduler
  csrc/device_lower/analysis/tma.cpp
  csrc/device_lower/analysis/tma.h
  csrc/device_lower/pass/index.cpp
  csrc/scheduler/hopper_multi_matmul.cpp
  tests/cpp/test_matmul.cpp
Labels: Matmuls

#3544 Add support for 32B and 64B swizzles to hopper matmul scheduler
  csrc/device_lower/pass/index.cpp
  csrc/scheduler/hopper_multi_matmul.cpp
  csrc/scheduler/hopper_multi_matmul.h
  tests/cpp/test_matmul_scheduler.cpp
  tests/cpp/utils.h
Labels: Matmuls

#3553 Refactor StMatrix Logic
  csrc/device_lower/pass/index.cpp
  csrc/scheduler/hopper_multi_matmul.cpp
  csrc/scheduler/hopper_multi_matmul.h
  tests/cpp/test_matmul_scheduler.cpp
  tests/cpp/utils.cpp
  tests/cpp/utils.h
Labels: Matmuls

#3552 Move StMatrix and TMA Store swizzle schedule functions to mma_utils
  csrc/scheduler/hopper_multi_matmul.cpp
  csrc/scheduler/hopper_multi_matmul.h
  csrc/scheduler/mma_utils.cpp
  csrc/scheduler/mma_utils.h
  tests/cpp/test_matmul.cpp
  tests/cpp/test_memory.cpp
  tests/cpp/test_mma.cpp
Labels: Matmuls

#3407 Support 2D pointwise scheduler with autotuning
  doc/dev/python_scheduling/autotune_pointwise.py
  doc/dev/python_scheduling/autotune_utils.py
Labels: Autotune

#3456 Support 2D inner reduction scheduler with autotuning
  doc/dev/python_scheduling/autotune_inner_reduction.py
  doc/dev/python_scheduling/autotune_utils.py
Labels: Autotune

#3574 Add MatmulParams::cluster_dims parameter
  csrc/scheduler/hopper_multi_matmul.cpp
  csrc/scheduler/hopper_multi_matmul.h
  csrc/scheduler/matmul_heuristic.h
Labels: Matmuls

#3558 Add MatmulParams::CircularBufferOptions::smem_circular_buffer_prefetch_gap
  csrc/scheduler/ampere_multi_matmul.cpp
  csrc/scheduler/hopper_multi_matmul.cpp
  csrc/scheduler/matmul_heuristic.h
  csrc/scheduler/matmul_heuristic_plugin.cpp
  csrc/scheduler/matmul_heuristic_plugin_api.h
  tests/cpp/test_matmul_scheduler.cpp
Labels: Matmuls

#3575 Implement basic split-k gemm for hopper matmul scheduler
  csrc/device_lower/utils.cpp
  csrc/scheduler/hopper_multi_matmul.cpp
  csrc/scheduler/hopper_multi_matmul.h
  csrc/tensor_view.cpp
  csrc/transform_rfactor.cpp
  tests/cpp/test_matmul_scheduler.cpp
Labels: Matmuls

#3487 Add reduction_unroll_factor to autotuning script
  doc/dev/python_scheduling/autotune_inner_reduction.py
Labels: Autotune

#3590 Fix double-scheduling of dc in HSS hopper matmuls
  csrc/scheduler/hopper_multi_matmul.cpp
  tests/cpp/test_matmul_scheduler.cpp
Labels: Matmuls

#3586 Update __truediv__ comment in python bindings.
  csrc/python_frontend/python_bindings.cpp
Labels: Python API

#3580 Schedule epilogue (for Hopper Matmul) by propagation backward from output - smem epilogue not supported.
  csrc/scheduler/hopper_multi_matmul.cpp
  csrc/scheduler/hopper_multi_matmul.h
  tests/cpp/test_matmul_scheduler.cpp
Labels: Matmuls

#3556 Initial resize scheduler
  CMakeLists.txt
  csrc/ir/nodes.cpp
  csrc/options.cpp
  csrc/options.h
  csrc/python_frontend/python_bindings.cpp
  csrc/scheduler/compile_time_info.h
  csrc/scheduler/pointwise.cpp
  csrc/scheduler/pointwise_utils.cpp
  csrc/scheduler/pointwise_utils.h
  csrc/scheduler/registry.cpp
  csrc/scheduler/resize.cpp
  csrc/scheduler/resize.h
  csrc/scheduler/scheduler_types.cpp
  csrc/scheduler/scheduler_types.h
  csrc/scheduler/tools/domain_map.cpp
  csrc/scheduler/tools/domain_map.h
  csrc/scheduler/transpose.cpp
  csrc/scheduler/utils.cpp
  csrc/scheduler/utils.h
  tests/cpp/test_alias.cpp
  tests/cpp/test_gpu3.cpp
  tests/cpp/test_resize.cpp
  tests/cpp/test_segmentation.cpp
  tests/python/test_python_frontend.py
Labels: rope

#3617 Add warp specialization to HSH_NT_128BSwizzle
  tests/cpp/test_matmul.cpp
Labels: Matmuls

#3611 Allow fusion of multiple exclusive resize ops
  csrc/scheduler/resize.cpp
  csrc/scheduler/tools/resize_utils.cpp
  csrc/scheduler/tools/resize_utils.h
  tests/cpp/test_gpu3.cpp
  tests/cpp/test_resize.cpp
Labels: rope

#3628 Add TN, NN, TT UseScheduler Matmul tests
  tests/cpp/test_matmul.cpp
Labels: Matmuls

#3645 Translate the repetition pattern to expand and reshape
  CMakeLists.txt
  csrc/preseg_passes/pre_segmenter.cpp
  csrc/preseg_passes/translate_repeat_to_expand.cpp
  csrc/preseg_passes/translate_repeat_to_expand.h
  tests/cpp/test_preseg_passes.cpp
Labels: rope

#3625 Resolve conflicts by recomputation
  csrc/scheduler/resize.cpp
  csrc/scheduler/tools/resize_utils.cpp
  csrc/scheduler/tools/resize_utils.h
  tests/cpp/test_resize.cpp
Labels: rope

#3656 C++ tests for some of the RoPE benchmark cases
  CMakeLists.txt
  tests/cpp/test_rope.cpp
Labels: rope
