Repository NVIDIA/Fuser, pull requests merged in 2024-08, with the labels that each got.

#2785 Include less.
  csrc/ops/utils.h
Labels: cleanup

#2797 Move AliasAnalysisTest to a separate file.
  CMakeLists.txt
  tests/cpp/test_alias.cpp
  tests/cpp/test_alias_analysis.cpp
Labels: cleanup

#2796 Clean up namespaces.
  csrc/executor_utils.cpp
Labels: cleanup

#2752 Support contiguous indexing
  CMakeLists.txt
  csrc/contiguity.cpp
  csrc/contiguity.h
  csrc/disjoint_set.h
  csrc/id_model/contiguity.cpp
  csrc/id_model/contiguity.h
  csrc/id_model/id_model_index_compute.cpp
  csrc/id_model/indexing.cpp
  csrc/id_model/indexing.h
  tests/cpp/test_indexing.cpp
Labels: idmodel

#2843 Support getPerDimLogicalIndices
  csrc/index_compute.cpp
  tests/cpp/test_indexing.cpp
Labels: rope

#2849 Adds a Graphviz graph printer for ValGraph
  csrc/id_model/indexing.cpp
  csrc/options.cpp
  csrc/options.h
  csrc/val_graph.cpp
  csrc/val_graph.h
Labels: idmodel
