Repository NVIDIA/Fuser, pull requests merged in 2025-01, with the labels that each got.

#3626 Ring Allgather + GEMM Overlap HostIR Implementation
  tests/cpp/test_multidevice_overlap.cpp
Labels: Multi-GPU

#3667 Create SetMaxNReg and Return kir nodes
  csrc/codegen.cpp
  csrc/device_lower/pass/index.cpp
  csrc/device_lower/pass/index.h
  csrc/device_lower/pass/inline_ptx.cpp
  csrc/dispatch.h
  csrc/kernel_ir.cpp
  csrc/kernel_ir.h
Labels: Matmuls

#3669 Add register sharing to warp-specialized circular buffering
  csrc/codegen.cpp
  csrc/codegen.h
  csrc/device_lower/analysis/circular_buffer.cpp
  csrc/device_lower/analysis/device_version.cpp
  csrc/device_lower/analysis/device_version.h
  csrc/device_lower/pass/circular_buffer.cpp
  csrc/ir/interface_nodes.h
  csrc/runtime/executor.cpp
  tests/cpp/test_circular_buffering.cpp
Labels: Matmuls

#3696 Enable register sharing only for hopper
  csrc/device_lower/analysis/device_version.cpp
  tests/cpp/test_circular_buffering.cpp
Labels: Matmuls

#3606 Lower distributed matmul to pipelined algorithm for fine-grained overlap: AG+GEMM layout
  csrc/host_ir/executor.cpp
  csrc/host_ir/executor.h
  csrc/host_ir/host_ir.h
  csrc/host_ir/lower.cpp
  csrc/host_ir/lower.h
  csrc/multidevice/utils.cpp
  csrc/preseg_passes/insert_reshardings.cpp
  csrc/preseg_passes/propagate_shardings.cpp
  csrc/preseg_passes/reorder_sharded_axis.cpp
  csrc/type.cpp
  csrc/type.h
  tests/cpp/test_multidevice_host_ir.cpp
  tests/cpp/test_multidevice_matmul.cpp
Labels: Multi-GPU

#3674 Add ResizeHeuristic
  csrc/scheduler/resize.cpp
  csrc/scheduler/resize_heuristic.h
Labels: rope

#3693 Reordering optimization in the resize scheduler
  csrc/scheduler/resize.cpp
  csrc/scheduler/resize_heuristic.h
  csrc/scheduler/utils.cpp
  csrc/scheduler/utils.h
Labels: rope

#3694 Resize scheduler: enable vectorization
  csrc/scheduler/resize.cpp
  csrc/scheduler/resize_heuristic.h
  tests/cpp/test_resize.cpp
Labels: rope

#3720 Extend the shortcut logic for loop promotion with cyclic graphs
  csrc/id_model/id_model.cpp
  csrc/id_model/id_model.h
  csrc/id_model/loop_promotion.cpp
  csrc/id_model/loop_promotion.h
  tests/cpp/test_id_model.cpp
Labels: rope

#3793 Update cuda runtime files for TMA Multicast and cluster
  CMakeLists.txt
  csrc/runtime/compiled_kernel.cpp
  runtime/cluster.cu
  runtime/mbarrier.cu
  runtime/memory.cu
Labels: Matmuls

#3791 Fix stmatrix scheduling for persistent GEMM
  csrc/device_lower/pass/index.cpp
  csrc/scheduler/mma_utils.cpp
Labels: Matmuls
