Repository NVIDIA/Fuser, pull requests merged in 2025-03, with the labels that each got.

#3989 Remove raw_ptrs_ from IrContainer
  csrc/ir/container.cpp
  csrc/ir/container.h
Labels: cleanup

#4039 Enable hard-coded index for LdMatrix and create basic copy tutorial
  CMakeLists.txt
  csrc/device_lower/analysis/predicate_elimination.cpp
  csrc/device_lower/pass/index.cpp
  csrc/scheduler/hopper_multi_matmul.cpp
  csrc/scheduler/mma_utils.cpp
  doc/dev/ldmatrix_stmatrix.md
  doc/dev/ldstmatrix/ldstmatrix_register_layout.svg
  doc/dev/ldstmatrix/ldstmatrix_to_tma.svg
  doc/dev/ldstmatrix/tma_layout.svg
  tests/cpp/test_matmul.cpp
  tests/cpp/test_memory.cpp
  tests/cpp/test_mma.cpp
  tests/cpp/tutorial_ldmatrix_stmatrix.cpp
Labels: Matmuls

#4084 Move debugging instructions from Wiki to main
  doc/dev/debug.md
Labels: documentation

#4088 Mark supports_segmentation=False in test_issue1273
  tests/python/test_python_frontend.py
Labels: bug

#4092 Update asan instructions to work with .so
  CMakeLists.txt
  doc/dev/debug.md
Labels: documentation

#4094 Disable register sharing with only one math warp group
  csrc/scheduler/hopper_multi_matmul.cpp
Labels: Matmuls

#4096 Enforce shared memory alignment for TMA LoadStoreOps
  csrc/device_lower/analysis/tma.h
  csrc/device_lower/pass/alias_memory.cpp
  csrc/mma_type.cpp
  csrc/mma_type.h
Labels: Matmuls

#3848 Enable resize scheduler by default
  csrc/options.cpp
  csrc/options.h
  csrc/preseg_passes/pre_segmenter.cpp
  csrc/scheduler/resize.cpp
  csrc/scheduler/tools/loop_domain_scheduler.cpp
  csrc/scheduler/tools/resize_utils.cpp
  tests/cpp/test_move_pad.cpp
  tests/cpp/test_resize.cpp
  tests/cpp/test_rope.cpp
  tests/python/test_python_frontend.py
Labels: rope

#4126 Temporarily skip the DeepSeek test
  tests/python/test_deepseek_v3.py
Labels: bug

#4127 Create fewer subfusions
  csrc/runtime/fusion_kernel_runtime.cpp
Labels: cleanup

#4069 Load Epilogue Inputs with LdMatrix in Hopper Matmul Scheduler
  csrc/device_lower/analysis/predicate_elimination.cpp
  csrc/kernel_ir.cpp
  csrc/scheduler/hopper_multi_matmul.cpp
  csrc/scheduler/matmul_heuristic.h
  csrc/scheduler/matmul_utils.cpp
  csrc/scheduler/mma_utils.cpp
  csrc/scheduler/mma_utils.h
  tests/cpp/test_matmul.cpp
  tests/cpp/test_memory.cpp
  tests/cpp/test_mma.cpp
Labels: Matmuls
