Repository NVIDIA/Fuser, pull requests merged in 2025-02, with the labels that each got.

#3616 Issue multiple wgmma operations when CTA k dim is a multiple of 16
  csrc/device_lower/pass/allocation.cpp
  csrc/device_lower/pass/insert_syncs.cpp
  csrc/scheduler/hopper_multi_matmul.cpp
  csrc/scheduler/hopper_multi_matmul.h
  csrc/scheduler/matmul_utils.cpp
  tests/cpp/test_matmul.cpp
  tests/cpp/test_matmul_scheduler.cpp
Labels: Matmuls

#3814 Use PredicateType::ElectSync with TMA store expressions
  csrc/device_lower/analysis/thread_predicate.h
  csrc/device_lower/pass/predicate.cpp
  csrc/device_lower/pass/unroll.cpp
  csrc/kernel.cpp
  csrc/kernel_ir.h
  csrc/predicate_compute.cpp
  csrc/predicate_compute.h
  tests/cpp/test_memory.cpp
Labels: Matmuls

#3828 Fix RoPE llama 3 backward
  csrc/ir/interface_nodes.h
  csrc/ir/internal_base_nodes.h
  csrc/ir/nodes.cpp
  csrc/scheduler/tools/loop_domain_scheduler.cpp
  csrc/tensor_view.cpp
  tests/cpp/test_rope.cpp
Labels: rope

#3751 Add a few benchmarks for concatenation.
  benchmarks/python/test_cat.py
  tests/python/test_ops.py
Labels: Thunder, Indexing Ops

#3862 Enable register sharing by default in matmul scheduler for better performance.
  csrc/scheduler/hopper_multi_matmul.cpp
Labels: Matmuls

#3863 Add WAR sync for wgmma expressions in compute warp
  csrc/device_lower/pass/insert_syncs.cpp
  tests/cpp/test_matmul.cpp
Labels: Matmuls

#3865 Fix WAR async issue with pipelined circular buffering
  csrc/device_lower/pass/insert_syncs.cpp
  tests/cpp/test_matmul.cpp
Labels: Matmuls

#3877 IdModel: Fix invalid promotion selection
  csrc/id_model/loop_promotion.cpp
  csrc/id_model/loop_promotion.h
  tests/cpp/test_id_model.cpp
Labels: idmodel

#3918 Add a script to run a single matmul configuration with custom MatmulParams
  csrc/python_frontend/python_bindings.cpp
  doc/dev/python_scheduling/profile_matmul.py
Labels: Matmuls

#3974 Remove swizzle argument from stMatrixForMmaOutput
  csrc/scheduler/hopper_multi_matmul.cpp
  csrc/scheduler/mma_utils.cpp
  csrc/scheduler/mma_utils.h
  tests/cpp/test_matmul.cpp
  tests/cpp/test_memory.cpp
  tests/cpp/test_mma.cpp
Labels: Matmuls
