Repository NVIDIA/Fuser, pull requests merged in 2025-06, with the labels that each got.

#4502 Modify IdModel Loop map to be aware of `stage_slice_position`
  csrc/device_lower/analysis/circular_buffer.cpp
  csrc/device_lower/analysis/circular_buffer.h
  csrc/device_lower/utils.cpp
  csrc/device_lower/utils.h
  csrc/id_model/id_model.cpp
  tests/cpp/test_circular_buffering_ping_pong.cpp
Labels: Matmuls

#4518 Add the bindings for reduction operations
  python/python_direct/ops.cpp
Labels: Python API, Direct Bindings

#4553 Backward contiguity analysis
  CMakeLists.txt
  csrc/contiguity.cpp
  csrc/contiguity.h
  csrc/id_model/contiguity.cpp
  csrc/id_model/contiguity.h
  tests/cpp/test_contiguity_id_model.cpp
  tests/cpp/test_indexing.cpp
Labels: idmodel

#4519 Move helper functions from python_frontend to python_common
  CMakeLists.txt
  python/python_common/python_utils.cpp
  python/python_common/python_utils.h
  python/python_common/translation_names.cpp
  python/python_common/translation_names.h
  python/python_frontend/fusion_definition.cpp
  python/python_frontend/fusion_definition.h
  python/python_frontend/translation.cpp
  python/python_frontend/translation_utils.cpp
  python/python_frontend/translation_utils.h
Labels: Python API, Direct Bindings

#4549 Enable TensorIndexer for matmul-related tests
  tests/cpp/test_circular_buffering.cpp
  tests/cpp/utils.h
Labels: idmodel

#4520 Create python reproducer from Fusion IR for nvfuser_direct
  CMakeLists.txt
  python/python_direct/bindings.cpp
  python/python_direct/bindings.h
  python/python_direct/python_translate.cpp
Labels: Python API, Direct Bindings

#4579 Generate ldstmatrix shared memory address using IdModel
  csrc/device_lower/pass/index.cpp
  csrc/id_model/id_model.cpp
  csrc/id_model/indexing.cpp
  csrc/id_model/indexing.h
  csrc/id_model/utils.h
  doc/dev/ldmatrix_stmatrix.md
Labels: Matmuls
