Repository NVIDIA/Fuser, pull requests merged in 2025-05, with the labels that each got.

#4357 [Hopper matmul] Limit grid traversal factor to prevent suboptimal CTA order
  csrc/scheduler/matmul_utils.cpp
Labels: Matmuls, H100 Perf

#4360 Refactor adjustMappingsForWarpSpecialization
  csrc/parallel_dimension_map.cpp
  csrc/parallel_dimension_map.h
  tests/cpp/test_circular_buffering.cpp
Labels: Matmuls

#4354 Pass -D even for default values
  python/utils.py
Labels: build

#4356 Fix reference reordering in resize scheduler
  csrc/scheduler/resize.cpp
  csrc/scheduler/utils.cpp
  tests/cpp/test_resize.cpp
Labels: rope

#4323 Create nvfuser_common package in build system
  .gitignore
  CMakeLists.txt
  examples/sinh_extension/setup.py
  examples/sinh_libtorch/README.md
  python/nvfuser_common/__init__.py
  python/nvfuser_common/utils.py
  python/utils.py
Labels: build, Direct Bindings

#4156 Create nvfuser_next extension
  .gitignore
  CMakeLists.txt
  python/nvfuser/__init__.py
  python/nvfuser_next/__init__.py
  python/python_next/bindings.cpp
  python/python_next/bindings.h
  python/python_next/extension.cpp
  python/utils.py
  tests/python/test_python_frontend.py
  tests/python_next/test_python_next.py
Labels: build, Python API, Direct Bindings

#4157 Create Statement, Expr, and Val bindings
  CMakeLists.txt
  python/python_next/bindings.cpp
  python/python_next/bindings.h
  python/python_next/ir.cpp
Labels: Python API, Direct Bindings

#4334 Select by warp id in AsyncWarp if Register Sharing is enabled
  csrc/parallel_dimension_map.cpp
  csrc/parallel_dimension_map.h
  csrc/predicate_compute.cpp
Labels: Matmuls

#4403 Create IterDomain, TensorDomain, and TensorView bindings
  python/python_next/bindings.cpp
  python/python_next/bindings.h
  python/python_next/extension.cpp
  python/python_next/ir.cpp
Labels: Python API, Direct Bindings

#4395 Enable same padding for non-register sharing warp specialization
  csrc/parallel_dimension_map.cpp
  csrc/parallel_dimension_map.h
  tests/cpp/test_circular_buffering.cpp
  tests/cpp/test_combined_inner_outer_reduction.cpp
Labels: Matmuls

#4390 New non-divisible split analysis for non-straightline logical-to-loop transformations
  csrc/device_lower/analysis/non_divisible_split.cpp
  csrc/device_lower/analysis/non_divisible_split.h
  csrc/device_lower/analysis/predicate_elimination.cpp
  csrc/device_lower/lower2device.cpp
  csrc/device_lower/lower2device.h
  csrc/id_model/indexing.cpp
  csrc/id_model/indexing.h
  tests/cpp/test_indexing.cpp
  tests/cpp/test_resize.cpp
Labels: idmodel

#4398 Enforce strict 128 thread padding for AsyncWarp
  csrc/parallel_dimension_map.cpp
  tests/cpp/test_circular_buffering.cpp
Labels: Matmuls

#4450 Rename nvfuser_next python module to nvfuser_direct
  .gitignore
  CMakeLists.txt
  python/nvfuser/__init__.py
  python/nvfuser_direct/__init__.py
  python/python_direct/bindings.cpp
  python/python_direct/bindings.h
  python/python_direct/extension.cpp
  python/python_direct/ir.cpp
  python/utils.py
  tests/python/test_python_frontend.py
  tests/python_direct/test_python_direct.py
Labels: Direct Bindings

#4460 Support Independent Compute Warp Groups
  CMakeLists.txt
  csrc/device_lower/analysis/circular_buffer.cpp
  csrc/device_lower/analysis/circular_buffer.h
  csrc/device_lower/pass/circular_buffer.cpp
  csrc/ir/interface_nodes.h
  csrc/parallel_dimension_map.cpp
  tests/cpp/test_circular_buffering_ping_pong.cpp
Labels: Matmuls

#4406 Add support for defineTensor
  CMakeLists.txt
  python/python_common/python_utils.cpp
  python/python_common/python_utils.h
  python/python_direct/bindings.cpp
  python/python_direct/bindings.h
  python/python_direct/enum.cpp
  python/python_direct/ir.cpp
  python/python_frontend/fusion_record.h
  python/python_frontend/python_bindings.cpp
Labels: Python API, Direct Bindings

#4236 Add missing non-divisible predicates in TensorIndexer
  csrc/bfs.h
  csrc/id_model/indexing.cpp
  csrc/id_model/indexing.h
  tests/cpp/test_indexing.cpp
  tests/cpp/test_memory.cpp
Labels: idmodel

#4407 Add binding for Fusion IrContainer
  CMakeLists.txt
  python/python_direct/bindings.cpp
  python/python_direct/bindings.h
  python/python_direct/runtime.cpp
Labels: Python API, Direct Bindings

#4408 Create bindings for FusionDefinition and Add Binary op
  CMakeLists.txt
  python/python_direct/bindings.cpp
  python/python_direct/bindings.h
  python/python_direct/ops.cpp
Labels: Python API, Direct Bindings

#4409 Create python FusionDefinition for nvfuser_next
  python/nvfuser_direct/__init__.py
  tests/python_direct/test_import.py
  tests/python_direct/test_python_direct.py
Labels: Python API, Direct Bindings
