Repository NVIDIA/Fuser, pull requests merged in 2025-04, with the labels that each got.

#4163 Support computeWith in TensorIndexer
  CMakeLists.txt
  csrc/device_lower/lower2device.cpp
  csrc/id_model/id_model.cpp
  csrc/id_model/id_model.h
  csrc/id_model/indexing.cpp
  tests/cpp/test_compute_with.cpp
Labels: idmodel

#4178 Expand ComputeAtMap exact and almost_exact disjointsets by IdModel
  csrc/compute_at_map.cpp
  csrc/device_lower/lower2device.cpp
Labels: idmodel

#4198 Fix the order of accumulating logical indices
  csrc/id_model/indexing.cpp
  csrc/id_model/indexing.h
  csrc/index_compute.cpp
  tests/cpp/test_rng.cpp
Labels: idmodel

#4183 Fix TensorIndexer for ldmatrix and stmatrix
  csrc/index_compute.cpp
  tests/cpp/test_memory.cpp
Labels: idmodel

#4195 Create block sync that runs inside of warp specialized IfThenElse
  csrc/codegen.cpp
  csrc/device_lower/pass/allocation.cpp
  csrc/device_lower/pass/insert_syncs.cpp
  csrc/kernel_ir.cpp
  csrc/kernel_ir.h
  csrc/parallel_dimension_map.cpp
  csrc/parallel_dimension_map.h
  tests/cpp/test_circular_buffering.cpp
Labels: Matmuls

#4214 Do not map splits when input extent is 1 in AlmostExact
  csrc/id_model/id_model.cpp
  tests/cpp/test_indexing.cpp
Labels: idmodel

#4234 Use set allocation domains if used by TMA or MmaOp
  csrc/device_lower/pass/allocation.cpp
  tests/cpp/test_matmul.cpp
Labels: idmodel

#4242 Prepare matmul schedulers for 2d grid traversal pattern
  csrc/python_frontend/python_bindings.cpp
  csrc/scheduler/ampere_multi_matmul.cpp
  csrc/scheduler/ampere_multi_matmul.h
  csrc/scheduler/hopper_multi_matmul.cpp
  csrc/scheduler/hopper_multi_matmul.h
  csrc/scheduler/matmul_heuristic.h
  csrc/scheduler/matmul_heuristic_plugin.cpp
  csrc/scheduler/matmul_utils.cpp
  tests/cpp/test_matmul.cpp
Labels: Matmuls

#4245 Enable TensorIndexer with the combined scheduler tests
  tests/cpp/test_combined_inner_outer_reduction.cpp
Labels: idmodel

#4221 Optimize mbarrier placement and enable register sharing with persistent matmul scheduler
  csrc/device_lower/analysis/circular_buffer.cpp
  csrc/device_lower/analysis/circular_buffer.h
  csrc/device_lower/pass/circular_buffer.cpp
  csrc/device_lower/pass/insert_syncs.cpp
  csrc/id_model/circular_buffer_indexing.cpp
  csrc/runtime/executor_utils.cpp
  csrc/scheduler/hopper_multi_matmul.cpp
  tests/cpp/test_circular_buffering.cpp
  tests/cpp/test_matmul.cpp
Labels: Matmuls

#4260 Create kir::Continue for persistent grid short-circuit
  csrc/codegen.cpp
  csrc/device_lower/pass/index.cpp
  csrc/device_lower/pass/index.h
  csrc/dispatch.h
  csrc/kernel_ir.cpp
  csrc/kernel_ir.h
Labels: Matmuls

#4257 Fix scheduling of split-K with smem_epilogue on Hopper
  csrc/scheduler/hopper_multi_matmul.cpp
  csrc/scheduler/hopper_multi_matmul.h
  csrc/scheduler/multi_matmul.cpp
  csrc/scheduler/multi_matmul.h
  tests/cpp/test_matmul.cpp
Labels: Matmuls

#4271 Create separate AsyncGroup helpers for fence, commit, and wait operations
  csrc/device_lower/pass/insert_syncs.cpp
  csrc/device_lower/utils.cpp
  csrc/device_lower/utils.h
Labels: Matmuls

#4270 Rename LoadWarp to AsyncWarp
  csrc/codegen.cpp
  csrc/device_lower/analysis/predicate_elimination.cpp
  csrc/device_lower/pass/circular_buffer.cpp
  csrc/device_lower/pass/insert_syncs.cpp
  csrc/ir/interface_nodes.h
  csrc/kernel_ir.h
  csrc/parallel_dimension_map.h
  csrc/predicate_compute.cpp
  csrc/scheduler/hopper_multi_matmul.cpp
  csrc/type.cpp
  csrc/type.h
Labels: Matmuls

#4275 Split insertion_info into Pipeline and WarpSpecialized parts
  csrc/device_lower/pass/circular_buffer.cpp
Labels: Matmuls

#4280 Create separate CircularBufferInserter for WarpSpecialized and Pipeline
  csrc/device_lower/pass/circular_buffer.cpp
Labels: Matmuls

#4289 Prefer static local to static global
  csrc/options.cpp
Labels: cleanup

#4285 Replace an ad-hoc toposort with stablyOrderedExprs
  csrc/runtime/fusion_kernel_runtime.cpp
Labels: cleanup

#4269 Forward full op
  csrc/fusion_segmenter.cpp
  csrc/fusion_segmenter.h
  tests/cpp/test_segmentation.cpp
Labels: rope

#4305 More precise WAR for resize vectorization
  csrc/scheduler/vectorize_helper.cpp
  tests/cpp/test_resize.cpp
Labels: rope

#4249 Create short-circuit in persistent outer for-loop to minimize cost of wave quantization.
  csrc/device_lower/analysis/circular_buffer.cpp
  csrc/device_lower/pass/circular_buffer.cpp
  tests/cpp/test_matmul.cpp
Labels: Matmuls

#4243 Add support for 2d grid swizzle in hopper matmul scheduler.
  csrc/scheduler/hopper_multi_matmul.cpp
  tests/cpp/test_matmul.cpp
Labels: Matmuls

#4307 Generalize the AsyncWarp selection predicate.
  csrc/device_lower/pass/circular_buffer.cpp
Labels: Matmuls

#4324 Minor change of the resize scheduler
  csrc/scheduler/resize.cpp
  csrc/scheduler/utils.cpp
  csrc/scheduler/utils.h
Labels: rope

#4312 Fix `wgmma` sync insertion for data-parallel.
  csrc/device_lower/pass/insert_syncs.cpp
  tests/cpp/test_matmul.cpp
Labels: Matmuls

#4328 Update environment variable comment in python/setup.py
  python/setup.py
Labels: build

#4330 Fix doc for asan build in the new system
  doc/dev/debug.md
Labels: documentation

#4345 Remove setup.py from doc
  doc/dev/debug.md
Labels: documentation

#4259 Fix resize scheduler with reshapes appearing after ref tensor
  csrc/scheduler/resize.cpp
  tests/cpp/test_resize.cpp
Labels: rope

#4333 Rename getRawLoad to getRawAsync
  csrc/codegen.cpp
  csrc/parallel_dimension_map.cpp
  csrc/parallel_dimension_map.h
Labels: Matmuls

#4342 Update sinh extension to use pyproject.toml
  examples/sinh_extension/README.md
  examples/sinh_extension/nvfuser_extension/__init__.py
  examples/sinh_extension/pyproject.toml
  examples/sinh_extension/setup.py
Labels: build

#4332 Skip ElectSync when creating predicate for TMA Store in PredicateCompute
  csrc/predicate_compute.cpp
  tests/cpp/test_memory.cpp
Labels: Matmuls

#4319 Always specify -DNVFUSER_BUILD_WITH_ASAN to cmake
  python/utils.py
Labels: build

#4325 Cleaning up scheduling of static repeat
  csrc/scheduler/resize.cpp
  csrc/scheduler/tools/static_repeat.cpp
  csrc/scheduler/tools/static_repeat.h
  tests/cpp/test_rope.cpp
Labels: rope
